### ISSUE TITLE
🐛 ImportError: cannot import name 'override' from 'typing' (/usr/lib/python3.10/typing.py) and cannot create pdf 

### ISSUE THREAD

**Issue by toilacube** [KevinNitroG/VNULIB-Downloader#23]
### 🐛 Mô tả lỗi

`ImportError: cannot import name 'override' from 'typing' (/usr/lib/python3.10/typing.py)`
It seems like package `override` from `typing` is not working in `python 3.10`? I have installed all the requirements inside a env. 

I tried to remove the `override` decorator from `download_img.py` since i think this decorator doens't required in this case. After that it works well until it downloaded all the images. When it tried to create pdf, this error happnens:
```
[INFO]: Creating PDF: "Downloads/2024-04-03 21-42-21-353662/2024-04-03 21-42-21-353662.pdf"
Process Process-2:
Traceback (most recent call last):
  File "/home/toilacube/VNULIB-Downloader/.env/lib/python3.10/site-packages/img2pdf.py", line 1817, in read_images
    imgdata = Image.open(im)
  File "/home/toilacube/VNULIB-Downloader/.env/lib/python3.10/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f700b780a90>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/toilacube/VNULIB-Downloader/src/modules/create_pdf.py", line 62, in _process
    pdf_file: bytes | None = img2pdf.convert(files)
  File "/home/toilacube/VNULIB-Downloader/.env/lib/python3.10/site-packages/img2pdf.py", line 2733, in convert
    ) in read_images(
  File "/home/toilacube/VNULIB-Downloader/.env/lib/python3.10/site-packages/img2pdf.py", line 1829, in read_images
    raise ImageOpenError(
img2pdf.ImageOpenError: cannot read input image (not jpeg2000). PIL: error reading image: cannot identify image file <_io.BytesIO object at 0x7f700b780a90>
```

### 💻 Hệ điều hành

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Khác

### 💁‍♂️ Python version

3.10.12

**Comment by KevinNitroG** [comment]
Alright I will remove `overide` decorator later. Thank you for having noticed me about that.

But have you tried the [pre built one](https://github.com/KevinNitroG/VNULIB-Downloader/releases/download/1.16/VNULIB-Downloader-ubuntu)? I don't know if it can run on distros other than ubuntu or not 😳

Btw if you want to develop the project, please use python >= 3.12 for the stability and ...sth. Because the project is based on that version.

Thôi nói tiếng việt đi ní project nhỏ xíu à :))

**Comment by toilacube** [comment]
The VNUlib website is not working properly now so i cannot test it :") I will reply later when the website is stable, just want to leave a message for you. 
Thank you for the hard work, this helps me a lot.

**Comment by KevinNitroG** [comment]
> It looks like the problem is from the vnulib itself. I try to download other documents and it works well (with python 3.12).
> 
> Here the document i tried to download:
> 
> ```
> https://ir.vnulib.edu.vn/flowpaper/services/view.php?doc=139139799493140943290946602841430103657&format=jpg&page=1&subfolder=13/91/39/
> ```

I take a look later. Just because I will be busy the next few days. Maybe the document you tried to download has a strange type that img2pdf (or even PIL) doesn't support, I guess.
Maybe this issue will end up with removing the `override` decorator only.

**Comment by KevinNitroG** [comment]
Removed `override` decorator in #28.
Thank you for giving feedback.
Hope this project help you more in the future :>

**Comment by KevinNitroG** [comment]
> It looks like the problem is from the vnulib itself. I try to download other documents and it works well (with python 3.12).
> 
> Here the document i tried to download:
> 
> ```
> https://ir.vnulib.edu.vn/flowpaper/services/view.php?doc=139139799493140943290946602841430103657&format=jpg&page=1&subfolder=13/91/39/
> ```

The document you couldn't download has some error pages.
Windows Explorer cannot show the preview of some images after I downloaded it.
![image](https://github.com/KevinNitroG/VNULIB-Downloader/assets/86353526/ad6234cb-5c2f-4891-a491-8679651c9f1b)

Check the original page links of those pages, seems that it's the document's problem.
![image](https://github.com/KevinNitroG/VNULIB-Downloader/assets/86353526/0512f0d7-0e44-42da-9d8e-c326651ad114)

**Comment by toilacube** [comment]
haha vnulib needs to hire some better developers and rebuild their system
